#' Synthetic National Early Warning Scores Data
#'
#' Synthetic NEWS data(\href{https://www.rcplondon.ac.uk/projects/outputs/national-early-warning-score-news-2}) as the results of the NHSR_synpop package.
#' These datasets have been synthetically generated by this package to be utilised in the NHSRDatasets package. 
#'
#' @docType data
#'
#' @keywords datasets synth_news_data
#'
#' @format Data frame with twelve columns
#' \describe{
#' \item{male}{character string containing gender code}
#' \item{age}{character, subcategory of names of groups where necessary, e.g. details of region: "East", details of age bands "15-44".}
#' \item{NEWS}{National Early Warning Score (NEWS)}
#' \item{syst}{Systolic BP - Systolic BP result}
#' \item{dias}{Diastolic Blood Pressure - result on NEWS scale}
#' \item{temp}{Temperature of patient}
#' \item{pulse}{Pulse of the patient}
#' \item{resp}{Level of response from the patient}
#' \item{sat}{SATS(Oxygen Saturation Levels) of the patient}
#' \item{sup}{Suppressed Oxygen}
#' \item{alert}{Level of alertness of patient}
#' \item{died}{Indicator to monitor patient death}
#' }
#'
#' @source Collected by Gary Hutson \email{g.hutson@nhs.net}, Mar-2021.
#'
#' @usage data(ons_mortality)
#'
#' @examples
#' library(magrittr)
#' library(dplyr)
#' data("synthetic_news_data")
#' syn_news %>% 
#'  glimpse()
#'

"synthetic_news_data"
